// E2E_BASE_URL=http://localhost:8097 node scripts/uat-709.mjs — #709: Centre closed days lists, adds and reopens. 375x812.
import { chromium } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
const APP = process.env.E2E_BASE_URL || 'http://localhost:8080';
const OUT = 'docs/design/uat/2026-10-10-centre-closed-days';
mkdirSync(OUT, { recursive: true });
const { token } = await (await fetch(`${APP}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'admin@example.com', password: 'demo1234' }) })).json();
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 375, height: 812 }, hasTouch: true, isMobile: true });
await ctx.addInitScript((t) => { localStorage.setItem('authToken', t); localStorage.setItem('authRole', 'Admin'); localStorage.setItem('authUser', 'admin@example.com'); }, token);
const p = await ctx.newPage();
const dlg = () => p.getByRole('dialog').last();
const res = [];
const check = (name, ok) => { res.push([name, ok]); console.log(ok ? 'pass' : 'FAIL', name); };
await p.goto(`${APP}/admin/timeoff`); await p.waitForTimeout(2500);
await p.getByText('Centre closed days').click(); await p.waitForTimeout(1500);
await p.screenshot({ path: `${OUT}/01-sheet.png` });
const t = await dlg().innerText();
check('the sheet lists the closed days coming and offers another', /CLOSED/i.test(t) && /Close another day/.test(t));
await dlg().getByRole('button', { name: /^Close another day/ }).click(); await p.waitForTimeout(600);
await dlg().getByLabel('Reason').fill('Staff retreat');
await p.screenshot({ path: `${OUT}/02-add.png` });
await dlg().getByRole('button', { name: 'Close the centre' }).click(); await p.waitForTimeout(1500);
check('the new day is listed', (await dlg().getByText('Staff retreat').count()) === 1);
await dlg().getByRole('button', { name: /Staff retreat/ }).click(); await p.waitForTimeout(1500);
check('a tap opens it again', (await dlg().getByText('Staff retreat').count()) === 0);
writeFileSync(`${OUT}/README.md`, `# #709 UAT, 10 Oct (demo seed)\n\n| Step | Result |\n|---|---|\n${res.map(([n, ok]) => `| ${n} | ${ok ? 'pass' : 'FAIL'} |`).join('\n')}\n\n![](01-sheet.png) ![](02-add.png)\n`);
await b.close();
process.exit(res.every(([, ok]) => ok) ? 0 : 1);
