// E2E_BASE_URL=http://localhost:8097 node scripts/uat-706.mjs — #706: the plan names what waits, Coming up folds, the main button grows at 200%. 375x812.
import { chromium } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
const APP = process.env.E2E_BASE_URL || 'http://localhost:8080';
const OUT = 'docs/design/uat/2026-10-10-availability-polish';
mkdirSync(OUT, { recursive: true });
const { token } = await (await fetch(`${APP}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'admin@example.com', password: 'demo1234' }) })).json();
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 375, height: 812 }, hasTouch: true, isMobile: true });
await ctx.addInitScript((t) => { localStorage.setItem('authToken', t); localStorage.setItem('authRole', 'Admin'); localStorage.setItem('authUser', 'admin@example.com'); }, token);
const p = await ctx.newPage();
const dlg = () => p.getByRole('dialog').last();
const res = [];
const check = (name, ok) => { res.push([name, ok]); console.log(ok ? 'pass' : 'FAIL', name); };
await p.goto(`${APP}/admin/timeoff`); await p.waitForTimeout(2500);
await p.getByText(/^Show \d+ more$/).scrollIntoViewIfNeeded();
await p.screenshot({ path: `${OUT}/01-list-folded.png` });
check('Coming up shows ten, the rest folded under Later', (await p.getByText(/^Show \d+ more$/).count()) === 1);
await p.getByRole('navigation', { name: 'Main' }).getByRole('button').first().click(); await p.waitForTimeout(800);
await dlg().getByText('Show staff').click(); await dlg().getByRole('checkbox').first().click();
await dlg().getByRole('button', { name: /^Next/ }).click(); await p.waitForTimeout(800);
await dlg().getByRole('button', { name: 'Some days' }).click();
const d = (n) => new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);
const dates = dlg().locator('input[type="date"]'); await dates.nth(0).fill(d(1)); await dates.nth(1).fill(d(2)); await p.waitForTimeout(1200);
await dlg().getByRole('button', { name: /^Save and fix/ }).click(); await p.waitForTimeout(5000);
const txt = await dlg().innerText().catch(() => '');
await dlg().getByText(/WAITING FOR YOU|Waiting for you/).scrollIntoViewIfNeeded().catch(() => {});
await p.screenshot({ path: `${OUT}/02-plan-waiting.png` });
check('the plan names what waits for you', /Waiting for you/i.test(txt));
await dlg().getByRole('button', { name: 'Not now' }).click();
await p.evaluate(() => { document.documentElement.style.fontSize = '200%'; }); await p.waitForTimeout(300);
await p.getByRole('navigation', { name: 'Main' }).getByRole('button').first().click(); await p.waitForTimeout(800);
await dlg().getByText('Show staff').click(); await dlg().getByRole('checkbox').nth(1).click();
await dlg().getByRole('button', { name: /^Next/ }).click(); await p.waitForTimeout(800);
await p.screenshot({ path: `${OUT}/03-form-200.png` });
const size = await dlg().getByRole('button', { name: /^Save and fix/ }).evaluate((e) => parseFloat(getComputedStyle(e).fontSize));
check('the main button label grows with the text (≥ 30px at 200%)', size >= 30);
writeFileSync(`${OUT}/README.md`, `# #706 UAT, 10 Oct (demo seed)\n\n| Step | Result |\n|---|---|\n${res.map(([n, ok]) => `| ${n} | ${ok ? 'pass' : 'FAIL'} |`).join('\n')}\n\n![](01-list-folded.png) ![](02-plan-waiting.png) ![](03-form-200.png)\n`);
await b.close();
process.exit(res.every(([, ok]) => ok) ? 0 : 1);
